# Generated by Django 3.1 on 2020-12-14 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(db_column='Course_id', max_length=10, primary_key=True, serialize=False)),
                ('course_name', models.CharField(blank=True, db_column='Course_name', max_length=100, null=True)),
            ],
            options={
                'db_table': 'course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Enrolled',
            fields=[
                ('batch_no', models.OneToOneField(db_column='Batch_no', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='student.batch')),
                ('teacher', models.CharField(blank=True, db_column='Teacher', max_length=30, null=True)),
            ],
            options={
                'db_table': 'enrolled',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_no', models.IntegerField(db_column='Topic_no', primary_key=True, serialize=False)),
                ('topic_name', models.CharField(db_column='Topic_name', max_length=255)),
                ('module_no', models.IntegerField(blank=True, db_column='Module_no', null=True)),
                ('weightage', models.FloatField(blank=True, db_column='Weightage', null=True)),
            ],
            options={
                'db_table': 'topic',
                'managed': False,
            },
        ),
    ]
